import unittest
from unittest.mock import patch

from pydantic import BaseModel
from sqlmodel import SQLModel, Session, create_engine, select

from app.ai_models import AgentRun, ModelCall
from app.ai_runtime import MODEL_PROFILES, ModelRuntime, ModelRuntimeError, ModelSettings
from app.api.system import get_model_profiles
from app.models import Approval, Project, ProjectRequirement
from app.services.planner_agent import generate_plan_for_project


class PlanResult(BaseModel):
    title: str


class ModelRuntimeTests(unittest.TestCase):
    def test_runtime_exposes_exactly_three_logical_profiles(self):
        self.assertEqual(MODEL_PROFILES, ("reasoning", "execution", "review"))

    def test_production_rejects_test_provider(self):
        with self.assertRaises(ModelRuntimeError):
            ModelSettings.from_environment(
                "reasoning",
                {
                    "OSAI_ENV": "production",
                    "OSAI_REASONING_PROVIDER": "test",
                    "OSAI_REASONING_MODEL": "fixture",
                },
            )

    def test_openai_compatible_response_is_schema_validated(self):
        def transport(url, headers, payload, timeout):
            self.assertEqual(url, "https://example.test/v1/chat/completions")
            self.assertEqual(headers["Authorization"], "Bearer secret")
            self.assertEqual(payload["model"], "test-model")
            return {
                "id": "request_123",
                "choices": [{"message": {"content": '{"title":"Plan"}'}}],
                "usage": {"prompt_tokens": 5, "completion_tokens": 3},
            }

        result, metadata = ModelRuntime(transport).invoke_json(
            "reasoning",
            system_prompt="Return JSON.",
            user_prompt="Create a plan.",
            response_model=PlanResult,
            environ={
                "OSAI_REASONING_PROVIDER": "openai_compatible",
                "OSAI_REASONING_MODEL": "test-model",
                "OSAI_REASONING_BASE_URL": "https://example.test/v1",
                "OSAI_REASONING_API_KEY": "secret",
            },
        )

        self.assertEqual(result.title, "Plan")
        self.assertEqual(metadata.provider_request_id, "request_123")
        self.assertEqual(metadata.input_tokens, 5)

    def test_planner_uses_model_output_and_records_auditable_run(self):
        engine = create_engine("sqlite://")
        SQLModel.metadata.create_all(engine)

        def transport(url, headers, payload, timeout):
            return {
                "id": "request_plan",
                "choices": [{"message": {"content": '{"title":"Real model plan","summary":"A structured plan generated by the configured model."}'}}],
                "usage": {"prompt_tokens": 10, "completion_tokens": 7},
            }

        environment = {
            "OSAI_REASONING_PROVIDER": "openai_compatible",
            "OSAI_REASONING_MODEL": "reasoning-model",
            "OSAI_REASONING_BASE_URL": "https://example.test/v1",
            "OSAI_REASONING_API_KEY": "super-secret",
        }
        with Session(engine) as session:
            project = Project(name="OSAI", description="Build an agent runtime")
            session.add(project)
            session.commit()
            session.add(ProjectRequirement(project_id=project.id, position=1, requirement_text="Use a real model."))
            session.commit()

            plan = generate_plan_for_project(
                session,
                project,
                runtime=ModelRuntime(transport),
                environ=environment,
            )

            agent_run = session.exec(select(AgentRun)).one()
            model_call = session.exec(select(ModelCall)).one()
            approval = session.exec(select(Approval)).one()
            self.assertEqual(plan.title, "Real model plan")
            self.assertEqual(agent_run.status, "succeeded")
            self.assertNotIn("super-secret", str(agent_run.input_payload))
            self.assertEqual(model_call.provider_request_id, "request_plan")
            self.assertEqual(approval.status, "pending")
            self.assertEqual(approval.requested_by, "agent:planner")

    def test_model_status_exposes_configuration_without_secrets(self):
        with patch.dict(
            "os.environ",
            {
                "OSAI_REASONING_MODEL": "reasoning-model",
                "OSAI_REASONING_BASE_URL": "https://example.test/v1",
                "OSAI_REASONING_API_KEY": "secret",
            },
            clear=True,
        ):
            profiles = get_model_profiles()

        self.assertEqual([profile.profile for profile in profiles], list(MODEL_PROFILES))
        self.assertTrue(profiles[0].configured)
        self.assertNotIn("secret", str(profiles[0].model_dump()))
        self.assertFalse(profiles[1].configured)
