import json
from typing import List, Mapping

from pydantic import BaseModel, Field
from sqlmodel import Session, select

from ..models import Plan, Project, ProjectRequirement
from ..ai_runtime import ModelRuntime
from .approval_service import request_plan_approval
from .agent_runtime import run_structured_agent


class GeneratedPlan(BaseModel):
    title: str = Field(min_length=3, max_length=240)
    summary: str = Field(min_length=10, max_length=4000)


def generate_plan_for_project(
    session: Session,
    project: Project,
    *,
    runtime: ModelRuntime | None = None,
    environ: Mapping[str, str] | None = None,
) -> Plan:
    """Generate a draft plan through the configured reasoning model."""
    requirements: List[ProjectRequirement] = session.exec(
        select(ProjectRequirement)
        .where(ProjectRequirement.project_id == project.id)
        .order_by(ProjectRequirement.position)
    ).all()
    existing_plan = session.exec(
        select(Plan).where(Plan.project_id == project.id).order_by(Plan.version.desc())
    ).first()
    generated, _ = run_structured_agent(
        session,
        agent_key="planner",
        project_id=project.id,
        response_model=GeneratedPlan,
        runtime=runtime,
        environ=environ,
        user_prompt=json.dumps(
            {
                "project": {"name": project.name, "description": project.description},
                "requirements": [
                    {"position": requirement.position, "text": requirement.requirement_text}
                    for requirement in requirements
                ],
                "instruction": "Create one plan title and concise execution summary. Do not include tasks.",
            }
        ),
    )
    plan = Plan(
        project_id=project.id,
        version=(existing_plan.version + 1) if existing_plan else 1,
        title=generated.title,
        summary=generated.summary,
        status="draft",
    )
    session.add(plan)
    session.commit()
    session.refresh(plan)
    request_plan_approval(
        session,
        plan=plan,
        actor="agent:planner",
        note="Plan generated by the Planner agent and awaiting operator review.",
        expected_plan_updated_at=plan.updated_at,
        idempotency_key=f"plan-generated:{plan.id}",
    )
    return plan
